FROM rust

RUN apt-get update

RUN apt-get install -y python3-pip

RUN pip3 install cargo-lambda

RUN apt-get install -y \
  curl \
  make \
  musl-tools \
  ;

RUN curl -O https://www.openssl.org/source/openssl-1.1.1q.tar.gz

RUN tar -xzvf openssl-*.tar.gz

ENV CC="musl-gcc \
  -idirafter /usr/include/ \
  -idirafter /usr/include/x86_64-linux-gnu/ \
  "

RUN cd openssl-*/ && ./Configure \
  linux-x86_64 \
  no-shared \
  && make && make install
