FROM node:18.9

RUN apt-get update

RUN apt-get install -y vim
RUN curl -Lo - https://go.dev/dl/go1.19.1.linux-amd64.tar.gz | tar -C /usr/local/ -xzf -
RUN git clone https://github.com/fatih/vim-go.git /root/.vim/pack/plugins/start/vim-go
RUN npm i -g @bazel/bazelisk
RUN npm i -g aws-cdk

RUN export PATH=$PATH:/usr/local/go/bin; vim +GoInstallBinaries +q

ARG HOME
ENV DAPPER_RUN_ARGS -v $HOME/.aws/:/root/.aws/
ENV PATH $PATH:/usr/local/go/bin
WORKDIR /source/

ENTRYPOINT ["./dapper.sh"]
